/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.7.1/userguide/multi_project_builds.html
 */

rootProject.name = "module-1"

// Removing the if check would result to error:
// Included build in /composite-full/dependency-1 has the same root project name 'dependency-1' as the main build.
if (gradle.parent == null) {
    includeBuild("../dependency-1")
}
